version: 2
models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:
      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique
          - not_null
      - name: host_id
        description: The hosts's id. References the host table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: Type of the apartment / room
        tests:
          - accepted_values:
              values:
                - Entire home/apt
                - Private room
                - Shared room
                - Hotel room
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value
  - name: mart_fullmoon_reviews
    description: sample description for mart_fulmoon_reviews model
    columns: []
  - name: dim_hosts_cleansed
    description: Cleansed table for the Airbnb hosts
    columns:
      - name: host_id
        description: Primary key for the host
        tests:
          - unique
          - not_null
      - name: host_name
        tests:
          - not_null
        description: Name of the host
      - name: is_superhost
        description: If the host is superhost
        tests:  
          - accepted_values:
              values: ['t', 'f']
      - name: created_at
        description: When the host entry was created
      - name: updated_at
        description: When the host entry was updated